/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyOrgs"];
        put?: never;
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssues"];
        put?: never;
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/orgs/{orgSlug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrgMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/members/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/members/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatuses"];
        put?: never;
        post: operations["createStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/statuses/{statusID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteStatus"];
        options?: never;
        head?: never;
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issue-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIssueTypes"];
        put?: never;
        post: operations["createIssueType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLabels"];
        put?: never;
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSprints"];
        put?: never;
        post: operations["createSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/sprints/{sprintID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSprint"];
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/sprints/{sprintID}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/sprints/{sprintID}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeSprint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIssue"];
        put?: never;
        post?: never;
        delete: operations["deleteIssue"];
        options?: never;
        head?: never;
        patch: operations["updateIssue"];
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComments"];
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/comments/{commentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch: operations["updateComment"];
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAttachments"];
        put?: never;
        post: operations["createAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/attachments/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/attachments/{attachmentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgSlug}/projects/{projectKey}/issues/{issueNumber}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIssueHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationID}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            expires_in: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            avatar_url?: string | null;
            /** @enum {string} */
            role: "admin" | "user";
            /** Format: date-time */
            created_at: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            logo_url?: string | null;
            /** @enum {string} */
            plan: "free" | "pro" | "enterprise";
            /** @enum {string} */
            my_role?: "owner" | "admin" | "member" | "guest";
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            /** @example PLX */
            key: string;
            name: string;
            description?: string | null;
            icon_url?: string | null;
            /** Format: uuid */
            lead_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Status: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
            /** @enum {string} */
            category: "todo" | "in_progress" | "done";
            position: number;
        };
        IssueType: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
            icon_url?: string | null;
        };
        Label: {
            /** Format: uuid */
            id: string;
            name: string;
            color: string;
        };
        Issue: {
            /** Format: uuid */
            id: string;
            number: number;
            title: string;
            description?: string | null;
            /** @enum {string} */
            priority: "urgent" | "high" | "medium" | "low" | "no_priority";
            /** Format: uuid */
            status_id: string;
            /** Format: uuid */
            type_id: string;
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: uuid */
            reporter_id: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: uuid */
            sprint_id?: string | null;
            story_points?: number | null;
            /** Format: date-time */
            due_date?: string | null;
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Comment: {
            /** Format: uuid */
            id: string;
            body: string;
            /** Format: uuid */
            author_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Sprint: {
            /** Format: uuid */
            id: string;
            name: string;
            goal?: string | null;
            /** @enum {string} */
            state: "active" | "closed" | "future";
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "assigned" | "mentioned" | "commented" | "status_changed";
            title: string;
            body?: string | null;
            read: boolean;
            /** Format: uuid */
            issue_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            filename: string;
            mime_type: string;
            size: number;
            /** Format: uuid */
            uploader_id: string;
            /** Format: date-time */
            created_at: string;
        };
        OrgMember: {
            /** Format: uuid */
            id: string;
            display_name: string;
            email: string;
            avatar_url?: string | null;
            /** @enum {string} */
            role: "owner" | "admin" | "member" | "guest";
            /** Format: date-time */
            joined_at: string;
        };
        IssueHistory: {
            /** Format: uuid */
            id: string;
            field: string;
            old_value?: string | null;
            new_value?: string | null;
            /** Format: uuid */
            actor_id: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: {
        orgSlug: string;
        projectKey: string;
        issueNumber: number;
        statusID: string;
        sprintID: string;
        commentID: string;
        attachmentID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    display_name?: string;
                    avatar_url?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMyOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of organizations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Organization"][];
                    };
                };
            };
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    slug?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    key?: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listIssues: {
        parameters: {
            query?: {
                status_id?: string;
                assignee_id?: string;
                sprint_id?: string;
                priority?: string;
            };
            header?: never;
            path: {
                orgSlug: string;
                projectKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Issue"][];
                    };
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: string;
                projectKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /** Format: uuid */
                    type_id: string;
                    /** Format: uuid */
                    status_id?: string;
                    /** @enum {string} */
                    priority?: "urgent" | "high" | "medium" | "low" | "no_priority";
                    description?: string;
                    /** Format: uuid */
                    assignee_id?: string;
                    /** Format: uuid */
                    sprint_id?: string;
                    story_points?: number;
                    /** Format: date-time */
                    due_date?: string;
                    label_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        number?: number;
                    };
                };
            };
        };
    };
    getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    logo_url?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOrgMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["OrgMember"][];
                    };
                };
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @enum {string} */
                    role?: "owner" | "admin" | "member" | "guest";
                };
            };
        };
        responses: {
            /** @description Invited */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                project?: string;
            };
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: Record<string, never>[];
                        total?: number;
                    };
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    icon_url?: string;
                    /** Format: uuid */
                    lead_id?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Status"][];
                    };
                };
            };
        };
    };
    createStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    color?: string;
                    category?: string;
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                statusID: components["parameters"]["statusID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                statusID: components["parameters"]["statusID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    color?: string;
                    category?: string;
                    position?: number;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIssueTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["IssueType"][];
                    };
                };
            };
        };
    };
    createIssueType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    color?: string;
                    icon_url?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Label"][];
                    };
                };
            };
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    color?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSprints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sprints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Sprint"][];
                    };
                };
            };
        };
    };
    createSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    goal?: string;
                    /** Format: date-time */
                    start_date?: string;
                    /** Format: date-time */
                    end_date?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                sprintID: components["parameters"]["sprintID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    goal?: string;
                    /** Format: date-time */
                    start_date?: string;
                    /** Format: date-time */
                    end_date?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                sprintID: components["parameters"]["sprintID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeSprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                sprintID: components["parameters"]["sprintID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    move_unfinished_to_sprint_id?: string;
                };
            };
        };
        responses: {
            /** @description Completed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
        };
    };
    deleteIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title?: string;
                    description?: string;
                    /** Format: uuid */
                    status_id?: string;
                    /** Format: uuid */
                    type_id?: string;
                    priority?: string;
                    /** Format: uuid */
                    assignee_id?: string;
                    /** Format: uuid */
                    sprint_id?: string;
                    story_points?: number;
                    /** Format: date-time */
                    due_date?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moveIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    status_id?: string;
                    position?: number;
                    /** Format: uuid */
                    sprint_id?: string;
                };
            };
        };
        responses: {
            /** @description Moved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Comment"][];
                    };
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
                commentID: components["parameters"]["commentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
                commentID: components["parameters"]["commentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Attachment"][];
                    };
                };
            };
        };
    };
    createAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename?: string;
                    mime_type?: string;
                    size?: number;
                    storage_key?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filename: string;
                    mime_type?: string;
                    size?: number;
                };
            };
        };
        responses: {
            /** @description Presigned upload URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        upload_url?: string;
                        storage_key?: string;
                        expires_in?: number;
                    };
                };
            };
        };
    };
    deleteAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
                attachmentID: components["parameters"]["attachmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIssueHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgSlug: components["parameters"]["orgSlug"];
                projectKey: components["parameters"]["projectKey"];
                issueNumber: components["parameters"]["issueNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["IssueHistory"][];
                    };
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Notification"][];
                    };
                };
            };
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All marked read */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
